### PR TITLE
Add maven support.

### PR DESCRIPTION
**Pull request by LaxWasHere**
Maven is a build system that is commonly used with Bukkit plugins. It allows for open source programs to be easily compiled on various systems without the need of finding jars and importing them as libraries.

I believe this would be a nice edition to MassiveCore, being that it is commonly used across various plugins, and people want development releases to new versions.

### CODE REVIEW

**Comment by boomboompower** [comment]
This would be great. Vouch

**Comment by willies952002** [comment]
Mavenize all the things \o/

**Comment by SirFaizdat** [comment]
+1

**Comment by MarkehMe** [comment]
Maven is slow. Really slow. If we were to implement a build system I would say we use Buck - which is a lot faster, and more configurable (https://buckbuild.com) 

It's not hard to compile yourself... reference spigot and anything in lib folder. Export to jar.. done

**Comment by aikar** [comment]
@MarkehMe I think you're thinking of Gradle.

Maven is very reasonable in speed.

There are better things to worry about than 15s build times.

It doesn't hurt to provide maven for those who wish to compile it, even if you don't use it yourself.

**Comment by LaxWasHere** [comment]
What could you have done in the 10 seconds to build the project? http://q.awsmpwrd.com/GMXu.png

Maven provides people to compile the project without the need to spend _MINUTES_ referencing spigot and anything in the lib folder. Besides, mavenized plugin can _AUTOMATICALLY_ be built using a build server like jenkins whenever a push is made in github which you can set-up much faster than it is to setup your workspace.

**Comment by mbax** [comment]
Fancy!

**Comment by gsand** [comment]
If I use maven, will I be able to compile massivecore just like I compile spiggit?

**Comment by MarkehMe** [comment]
How about we start with a _disclaimer_: 
I am a **volunteer** developer at MassiveCraft and I am **not paid** but simply doing what I do for the love of Factions and MassiveCraft projects. I treat this as a hobby, in my spare time, and, for fun. I came on board due to me trying to make Factions more awesome with my FactionsPlus project (currently in the process of abandoning it). Factions is freeware, yes, I'm not asking you to pay for it, but it's free, and it's also not a primary source of income for MassiveCraft or it's developers. Freeware: yes. Asking for money: no. (@willies952002) 

I feel like you're all taking me the wrong way, so I'll add emojis 😄  🐱  👱  so we can have a better understanding.

@aikar Gradle is better again yes 🎉 I love Gradle, but I'm the sort of person who likes to stay on top of new technologies - maybe obsessively 😏  that's like sticking to Browserify when there are more faster and powerful alternatives like JSPM 😆  I just don't like the idea of that.

I'm not just referring to speed, but Buck is quite powerful and configurable. Let's not develop technophobia here, right?! 😆  😜 

@LaxWasHere please 😮  stop being so defensive in these issue tickets, we're all trying to build contribute in some awesome way 😄 . I volunteer my time to this project and make no money off it 😪 , so try not to be ~~such a dick~~ un-constructive (_this is how you're coming off by the way_) 😆  in every issue ticket you contribute to. I can respond with a meme here too:

Calm Down Pls

When you have the amount of projects that MassiveCraft has (and there are more than the listed ones) using something like Buck would be great IMO! 

Anyway, lets real talk right now ... 

### You can already use Maven! 🎉 🎉 🎉 🎉 🎉 🎉 

I think this is the third time I've explained this, but now - heres a script to prove it.

If you haven't realised by now you can actually use the current git repo in maven projects, you don't need to "Mavenize" this codebase. But just create a local codebase and add a few things to the git ignore. 

**massive-maven.sh** (I wrote this in about 5 minutes, probably dodgy) 
```bash
function do_massive_maven_setup() {
    # Setup maven style directories
    echo "Creating Maven directories";
    mkdir -p "./$1/src/main/java";
    ln -s "./$1/src/com/" "./$1/src/main/java/com";
    # Create pom.xml file
    touch "./$1/pom.xml";
    # Add stuff to .gitignore so we can safely pull in the future
    echo '' >> "$1/.gitignore";
    echo '# Massive Maven Stuff ' >> "$1/.gitignore";
    echo 'pom.xml' >> "$1/.gitignore";
    echo 'src/main/' >> "$1/.gitignore";
}

echo "=== MASSIVE MAVEN START ===";
echo "";
echo "!! This is NOT an official script, and is in no way supported by MassiveCraft !!";
echo "";

if [ ! -d "./$1" ]; then
    echo "Cloning repo";
    git clone "https://github.com/MassiveCraft/$1.git" "./$1" && do_massive_maven_setup $1 $1
fi
# Update repo
git -C "./$1" pull;

echo "";
echo "=== MASSIVE MAVEN FINISH ===";
```

Usage:

```
$ sh massive-maven.sh Vampire
=== MASSIVE MAVEN START ===

!! This is NOT an official script, and is in no way supported by MassiveCraft !!

Cloning repo
Cloning into './Vampire'...
remote: Counting objects: 3157, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 3157 (delta 10), reused 0 (delta 0), pack-reused 3126
Receiving objects: 100% (3157/3157), 2.69 MiB | 392.00 KiB/s, done.
Resolving deltas: 100% (1421/1421), done.
Checking connectivity... done.
Creating Maven directories
Already up-to-date.

=== MASSIVE MAVEN FINISH ===

~/src/test ⌚ 12:46:22
$ ls Vampire 
README.md  media      plugin.yml pom.xml    src

```

Now update the pom.xml file, and go. A symbolic link was created: /src/main/java/com -> /src/com

To update it to the latest commit you just re-run the same thing ```sh massive-maven.sh Vampire``` and it will detect the Vampire folder exists and update it. 

Then I believe you can use a local repository in your own projects/whatever. 😄

**Comment by MatthewM** [comment]
@MarkehMe I typically don't inject my opinion to other's projects, however, I do wish to know why you guys are against adding a PR that's harmless and would help others to contribute to the project. Does the parent server (MassiveCraft), your superiors (people higher up on the dev chain), or others involved dislike allowing others to easily assist them? If so, could you please answer why this was released in a public repo as it was. 

Also, seeing as you don't have  a LICENSE file in the project, I'm tempted to send you a PR of a license since you seem to be missing one - is there a specific license that you would like?

On the other hand, if your team doesn't want to use Maven at all, you could tell @LaxWasHere to revert the change he made in plugin.yml and then accept the PR to allow those that do like Maven to be able to use it. I don't see any harm in doing so.

**Comment by MarkehMe** [comment]
@MatthewM it's under **GNU Lesser General Public License version 3 (LGPLv3)** I believe. 😃 

There may not be any harm in doing so but I doubt it will go any further. Out of my control for one, but the way @LaxWasHere has approached recent pull requests and comments on issues is not going to convince any developer, or be taken seriously. 

If you really want to use Maven yourself you can add a pom.xml and place it in your .gitignore I guess. My script will automatically do this for you if you want it in a repo. 

I suppose we should add support for a lot of common build systems then? Ant, Gradle, Maven, Buck, etc.. ok - no, that's just getting messy. I see an issue starting here already. 😪 

If we want to try again in a more mature matter - maybe it will be considered by other developers, but I do think that we need to seriously consider how to go about this. 😄 

Seeing this has gotten out of hand, I will close and lock this. Before opening a new pull request or issue ticket 

MassiveCraft supports all contributions - it helps a lot, but we do need to follow standards: https://www.massivecraft.com/tech-standards

**Pull request closed without merging**
