### PR TITLE
Disable using "/mstore sponsor" for operators by default

### PR DESCRIPTION
**Pull request by LaxWasHere**

### CODE REVIEW

**Comment by ravkr** [comment]
We need that change! it is very important!

**Comment by sweepyoface** [comment]
-1

**Comment by SirFaizdat** [comment]
Commit message should be "change massivecore.sponsor permission to be not default" or something along those lines.

**Comment by magnusulf** [comment]
Do you mind sharing why this change is needed? Per default we give all permissions to operators, that is kinda the point of operators.

**Comment by RoboMWM** [comment]
The message also clutters server logs; this PR in my opinion doesn't go far enough. 👍 for at least getting the ball rolling in the right direction.

**Comment by MarkehMe** [comment]
Thank you for your support!! 😄 

We really love it when people want to help out with the Factions plugin. However, I think disabling this permission by default will annoy _a lot_ of server owners. 

As this is the permission required to run the ```/mcore sponsor``` command - which disables the message. 🐳

**Comment by LaxWasHere** [comment]
Having the message enabled by default is annoying enough so why not take the owners ability to disabled it? That way the advertisers can give the developers more money and everyone will be happy.

**Comment by MarkehMe** [comment]
Hey Lax - I don't think thats a very good idea. 

_Please_ consider that although you're happy to leave the message enabled that not everyone would be. 

Thank you again. I will lock this conversation for now so that other developers can consider your feature request.

**Pull request closed without merging**
